services:
  - type: web
    name: ai-music-generator
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app"
    healthCheckPath: /health
