# Alternative Rock Sub-Genre Configuration
# Inherits from rock parent with alternative characteristics

parent: "rock"
name: "alternative_rock"
display_name: "Alternative Rock"
description: "Non-mainstream rock with diverse influences and experimental elements"

# Override BPM for alt rock feel
bpm:
  min: 90
  max: 160
  preferred: 115

# Override instruments for alternative focus
instruments:
  required: ["KICK", "SNARE", "BASS_PICK", "GUITAR_DISTORTED", "VOCALS"]
  optional: ["ACOUSTIC_STRUM", "PIANO", "STRINGS", "EFFECTS"]

# Override groove for alternative pocket
groove:
  swing: 0.05          # Minimal swing
  pocket: "alternative" # Non-conventional feel
  energy: "varied"     # Dynamic energy changes

# Override mix targets for alternative sound
mix_targets:
  lufs: -11.0          # Less compressed than mainstream rock
  spectral_centroid_hz: 2400

# Override mix style for alternative production
mix_style:
  compression_heavy: "light"      # Less compressed
  saturation_level: 0.3
  stereo_enhancement: "balanced"

# Override dynamics for alternative feel
dynamics:
  crest_factor: 13.0   # More dynamic range
  rms_target: -20.0