# K-Pop/J-Pop Genre Parent Configuration
# Asian pop music with polished production and varied influences

name: "kpop_jpop"
display_name: "K-Pop/J-Pop"
description: "Asian pop music featuring polished production, varied musical influences, and dynamic arrangements"

# Default BPM range
bpm:
  min: 90
  max: 140
  preferred: 115

# Key signatures
keys:
  major: ["C", "G", "D", "A", "F", "Bb"]
  minor: ["Am", "Em", "Bm", "F#m", "Dm", "Gm"]
  preferred: ["C", "G", "Am", "Em"]

# Time signatures
time_signatures:
  primary: "4/4"
  secondary: ["3/4", "6/8"]

# Groove characteristics
groove:
  swing: 0.05       # Slight swing
  pocket: "tight"   # Very tight, precise timing
  energy: "dynamic" # Dynamic energy changes
  dynamics: "dramatic" # Dramatic dynamic shifts

# Instrument roles
instruments:
  required: ["KICK", "SNARE", "BASS_SYNTH", "PIANO", "SYNTH_LEAD"]
  optional: ["STRINGS", "BRASS", "GUITAR", "TRADITIONAL"]
  lead_instruments: ["vocals", "synth_lead", "piano", "strings"]
  rhythm_section: ["drums", "bass", "synth_pad"]

# Chord progressions
chord_progressions:
  common:
    - ["C", "Am", "F", "G"]       # I-vi-IV-V
    - ["Am", "F", "C", "G"]       # vi-IV-I-V
    - ["C", "G", "Am", "F"]       # I-V-vi-IV
    - ["F", "G", "Em", "Am"]      # IV-V-iii-vi
  
  complexity: "varied"            # From simple to complex

# Song structure
structure:
  common_forms:
    - ["INTRO", "VERSE", "PRECHORUS", "CHORUS", "VERSE", "PRECHORUS", "CHORUS", "BRIDGE", "CHORUS", "OUTRO"]
    - ["INTRO", "VERSE", "BUILDUP", "DROP", "VERSE", "BUILDUP", "DROP", "BREAKDOWN", "FINAL_CHORUS"]
  
  section_lengths:
    INTRO: 8
    VERSE: 16
    PRECHORUS: 8
    BUILDUP: 8
    CHORUS: 16
    DROP: 16
    BRIDGE: 16
    BREAKDOWN: 8
    OUTRO: 8

# Mix targets
mix_targets:
  lufs: -10.0
  true_peak_db: -0.8
  spectral_centroid_hz: 2300
  spectral_centroid_range:
    min: 1900
    max: 2800
  stereo_ms_ratio: 0.8
  stereo_ms_range:
    min: 0.6
    max: 1.0

# Frequency balance
frequency_balance:
  low_energy: 0.4      # Clean, punchy bass
  mid_energy: 0.5      # Vocal clarity
  high_energy: 0.45    # Bright, sparkly

# Dynamic characteristics
dynamics:
  crest_factor: 7.0    # Heavy compression for loudness
  rms_target: -17.0

# Mix style
mix_style:
  compression_heavy: "heavy"
  saturation_level: 0.25
  stereo_enhancement: "wide"
  reverb_usage: "moderate"
  delay_usage: "moderate"

# QA thresholds
qa_thresholds:
  min_hook_strength: 0.8         # Very catchy required
  min_harmonic_stability: 0.75
  min_arrangement_contrast: 0.8  # Dynamic changes important
  min_mix_quality: 0.85          # High production standards
  min_style_match: 0.8
  
  max_repetition_ratio: 0.35     # Less repetitive
  min_melodic_interest: 0.8      # Strong melodies
  max_timing_variance: 0.05      # Very tight timing

# Sub-genres
sub_genres:
  - "kpop_dance"
  - "kpop_ballad"
  - "jpop_idol"
  - "jpop_rock"
  - "city_pop"